// <auto-generated />
using System;
using ApiManagmentBasket;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiManagmentBasket.Migrations
{
    [DbContext(typeof(OrderManagmentDbContext))]
    [Migration("20190523073853_initial-create")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiManagmentBasket.Basket", b =>
                {
                    b.Property<int>("BasketId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("BasketId");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("ApiManagmentBasket.Customer", b =>
                {
                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150);

                    b.Property<string>("Address");

                    b.Property<DateTime>("Dob");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name");

                    b.Property<DateTime>("RegisterDay");

                    b.HasKey("Email");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ApiManagmentBasket.CustomerBaskets", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasMaxLength(150);

                    b.Property<int>("BasketId");

                    b.HasKey("CustomerId", "BasketId");

                    b.HasIndex("BasketId");

                    b.ToTable("CustomerBaskets");
                });

            modelBuilder.Entity("ApiManagmentBasket.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BasketId");

                    b.Property<int>("Category");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.HasKey("ProductId");

                    b.HasIndex("BasketId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ApiManagmentBasket.CustomerBaskets", b =>
                {
                    b.HasOne("ApiManagmentBasket.Basket", "Basket")
                        .WithMany("customerBaskets")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ApiManagmentBasket.Customer", "Customer")
                        .WithMany("customerBaskets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ApiManagmentBasket.Product", b =>
                {
                    b.HasOne("ApiManagmentBasket.Basket")
                        .WithMany("Cart")
                        .HasForeignKey("BasketId");
                });
#pragma warning restore 612, 618
        }
    }
}
